import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Frontend Mentor | Tip calculator app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        Bill Select Tip % 5% 10% 15% 25% 50% Custom Number of People Tip Amount
        / person Total / person Reset
        <footer className="attribution">
          Challenge by{' '}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            target="_blank"
            rel="noreferrer"
          >
            Frontend Mentor
          </a>
          . Coded by{' '}
          <a href="https://www.frontendmentor.io/profile/KatherineEbel">
            Katherine Ebel
          </a>
          .
        </footer>
      </main>
    </div>
  )
}

export default Home
